var d=new function(){this.animation=100*Math.random();this.visible=!0;this.opacity=1;this.color=null;this.oa=this.pa=0;this.ha=[];this.R=!1;window.addEventListener("load",function(){d.R||(d.R=!0,d.P())});setTimeout(function(){d.R||(d.R=!0,d.P())},3E3);this.ra=function(a){a.addEventListener("load",function(){++d.oa;d.P()});++this.pa};this.ka=function(a){this.ha.push(a);++this.pa};this.na=function(){return this.oa>=this.pa&&this.R&&e.loaded};this.P=function(){this.na()&&(this.visible=!1,aa.show(),m.show("<b>W A S D / MOUSE</b> - move<br><b>Q E / SCROLL</b> - zoom"),
ba.show())};this.update=function(a){this.animation+=a;this.visible||(this.opacity=Math.max(0,this.opacity-4*a));for(a=0;a<this.ha.length;++a)this.ha[a].loaded&&(++this.oa,this.P(),this.ha.splice(a,1),--a)};this.F=function(a){this.color=a.color};this.J=function(a){if(0<this.opacity){var b=a.canvas.width/2,c=a.canvas.height-180*r.j;a.globalAlpha=this.opacity;a.translate(b,c);a.shadowColor=this.color;a.shadowBlur=8*r.j;a.rotate(3.4823*this.animation);a.beginPath();a.arc(0,0,40*r.j,0,4.5);a.strokeStyle=
this.color;a.lineWidth=2*r.j;a.lineCap="round";a.stroke();a.rotate(3.4823*-this.animation);a.rotate(4.1822*-this.animation);a.beginPath();a.arc(0,0,30*r.j,0,4.5);a.strokeStyle=this.color;a.lineWidth=2*r.j;a.lineCap="round";a.stroke();a.rotate(4.1822*this.animation);a.shadowBlur=0;a.translate(-b,-c);a.globalAlpha=1}}},u=new function(){this.ea=this.destination=this.context=null;this.Aa=!1;this.$=null;this.V=[];this.O=[];this.ca=null;try{window.AudioContext=window.AudioContext||window.webkitAudioContext,
this.context=new AudioContext,this.destination=this.context.createDynamicsCompressor(),this.destination.connect(this.context.destination)}catch(a){console.error("Failed to initialize sound: "+a)}this.M=function(){if(null!=this.context)this.ea=new Audio("audio/noise.ogg","audio/noise.mp3"),d.ka(this.ea),this.$=new Audio("audio/collision.ogg","audio/collision.mp3"),d.ka(this.$),this.ca=new Audio("audio/level.ogg","audio/level.mp3"),d.ka(this.ca);else try{var a=document.createElement("audio");a.autoplay=
!0;a.loop=!0;a.innerHTML+='<source src="audio/noise.ogg" type="audio/ogg">';a.innerHTML+='<source src="audio/noise.mp3" type="audio/mp3">';document.body.appendChild(a);a.play()}catch(b){}};this.La=function(a,b){if(null!=this.context){for(var c=null,f=0;f<this.O.length;++f){var g=this.O[f];if(g.Ga==a&&g.Ha==b){this.O.splice(f,1);c=g;break}}f=Math.pow(Math.min(a.a,b.a)/t.a,2);g=Math.min(10,.5/(Math.min(a.a,b.a)/t.a));null==c?null!=this.$.buffer&&20>this.V.length&&(c={source:null,gain:null,Ga:a,Ha:b},
c.source=u.context.createBufferSource(),c.source.buffer=this.$.buffer,c.source.loop=!0,c.gain=u.context.createGain(),c.gain.gain.value=f,c.gain.connect(u.destination),c.source.connect(c.gain),c.source.playbackRate.value=g,c.source.start(0),this.V.push(c)):(c.gain.gain.setTargetAtTime(f,0,.01),c.source.playbackRate.setTargetAtTime(g,0,.1),this.V.push(c))}};this.Ma=function(){if(null!=this.context){if(null!=this.ca.buffer){var a=u.context.createBufferSource();a.buffer=this.ca.buffer;var b=u.context.createGain();
b.gain.value=1;b.connect(u.destination);a.connect(b);a.start(0)}}else{a=null;try{a=document.createElement("audio"),a.onended=function(){document.body.removeChild(this)},a.autoplay=!0,a.innerHTML+='<source src="audio/level.ogg" type="audio/ogg">',a.innerHTML+='<source src="audio/level.mp3" type="audio/mp3">',document.body.appendChild(a),a.play()}catch(c){null!=a&&document.body.removeChild(a)}}};this.update=function(){if(null!=this.context){this.context.listener.setOrientation(0,0,-1,0,1,0);this.context.listener.setPosition(v.f,
v.i,128);for(var a=0;a<this.O.length;++a)this.O[a].gain.gain.setTargetAtTime(0,0,.1),this.O[a].source.stop(this.context.currentTime+5);this.O=this.V;this.V=[];if(!this.Aa&&null!=this.ea.buffer){a=u.context.createBufferSource();a.buffer=this.ea.buffer;a.loop=!0;var b=u.context.createGain();b.gain.value=.8;b.connect(u.destination);a.connect(b);a.start(0);this.Aa=!0}}}};
function Audio(a,b){this.buffer=null;this.loaded=!1;var c=this;if(null!=u.context)try{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=function(){try{u.context.decodeAudioData(this.response).then(function(g){c.buffer=g;c.loaded=!0})["catch"](function(){if(b){var g=new XMLHttpRequest;g.open("GET",b,!0);g.responseType="arraybuffer";g.onload=function(){u.context.decodeAudioData(this.response).then(function(h){c.buffer=h;c.loaded=!0})["catch"](function(){c.loaded=!0})};
g.send()}else c.loaded=!0})}catch(g){try{u.context.decodeAudioData(this.response,function(h){c.buffer=h;c.loaded=!0},function(){if(b){var h=new XMLHttpRequest;h.open("GET",b,!0);h.responseType="arraybuffer";h.onload=function(){u.context.decodeAudioData(this.response,function(n){c.buffer=n;c.loaded=!0},function(){c.loaded=!0})};h.send()}else c.loaded=!0})}catch(h){c.loaded=!0}}};f.send()}catch(g){c.loaded=!0,console.error(g)}else c.loaded=!0}
var ca=new function(){this.image=new Image;d.ra(this.image);this.image.pattern=null;this.image.src="images/background.png";this.Ua=-1!=navigator.userAgent.toLowerCase().indexOf("chrome");this.offsetY=this.offsetX=0;this.animation=100*Math.random();this.N=[];for(var a=0;1024>a;++a){for(var b=[],c=0;8>c;++c)b.push(.75+.5*Math.random());this.N.push(b)}this.update=function(f){this.animation+=8E-4*f};this.L=function(f,g,h,n){null==this.image.pattern&&this.image.complete&&(this.image.pattern=f.createPattern(this.image,
"repeat"));if(null!=this.image.pattern){g=24*Math.pow(2,g-x);f.scale(g,g);f.translate(2048*h,2048*n);var l=v.f/g-f.canvas.width/2/v.zoom/r.j/g-2048*h,k=v.i/g-f.canvas.height/2/v.zoom/r.j/g-2048*n,p=(f.canvas.width+1)/v.zoom/r.j/g,w=(f.canvas.height+1)/v.zoom/r.j/g;if(this.Ua){l=Math.floor(l/this.image.width)*this.image.width;k=Math.floor(k/this.image.height)*this.image.height;for(var C=0;C<=Math.ceil(p/this.image.width);++C)for(var q=0;q<=Math.ceil(w/this.image.height);++q)f.drawImage(this.image,
l+C*this.image.width,k+q*this.image.height)}else f.fillStyle=this.image.pattern,f.fillRect(l,k,p,w);f.translate(2048*-h,2048*-n);f.scale(1/g,1/g)}};this.J=function(f){f.fillStyle="rgb(0,0,"+Math.floor(34*Math.max(0,Math.min(1,1-Math.pow(Math.pow(2,x)/v.zoom,.1)/Math.pow(1E26,.1))))+")";f.fillRect(0,0,f.canvas.width,f.canvas.height);f.translate(Math.floor(f.canvas.width/2),Math.floor(f.canvas.height/2));f.scale(v.zoom*r.j,v.zoom*r.j);f.translate(-v.f,-v.i);var g=x+1-3*Math.log(8*v.zoom)/Math.log(8),
h=4*Math.floor(g/4),n=4*Math.ceil(g/4);g=(g-h)/(n-h);isNaN(g)&&(g=0);var l=this.N[Math.abs(this.N.length+h/4)%this.N.length],k=this.N[Math.abs(this.N.length+n/4)%this.N.length];f.globalAlpha=.1*(1-g);this.L(f,h,this.offsetX+this.animation*l[0],this.offsetY+this.animation*l[4]);this.L(f,h,this.offsetX-this.animation*l[1],this.offsetY+this.animation*l[5]);this.L(f,h,this.offsetX+this.animation*l[2],this.offsetY-this.animation*l[6]);this.L(f,h,this.offsetX-this.animation*l[3],this.offsetY-this.animation*
l[7]);f.globalAlpha=.1*g;this.L(f,n,this.offsetX+this.animation*k[0],this.offsetY+this.animation*k[4]);this.L(f,n,this.offsetX-this.animation*k[1],this.offsetY+this.animation*k[5]);this.L(f,n,this.offsetX+this.animation*k[2],this.offsetY-this.animation*k[6]);this.L(f,n,this.offsetX-this.animation*k[3],this.offsetY-this.animation*k[7]);f.globalAlpha=1;f.setTransform(1,0,0,1,0,0)}};
function y(){this.volume=this.o=this.m=this.i=this.f=0;this.a=10;this.T=1;this.color=this.C=this.w=this.saturation=this.u=null;z(this);da(this);null!=this.color&&null!=this.C||ea(this)}var A=[];function fa(a){A.push({u:a.u,saturation:a.saturation,w:a.w,color:a.color,C:a.C})}function ha(a){a.a=Math.pow(a.volume/(4/3)/Math.PI,1/3)}function z(a){a.volume=4/3*Math.PI*Math.pow(a.a,3)}y.prototype.I=function(){return B.I(x,this.a)};
y.prototype.update=function(a){this.T=Math.min(1,this.T+6*a);this.f+=this.m*a;this.i+=this.o*a};function da(a){if(0<A.length){var b=A.splice(Math.floor(Math.random()*A.length),1)[0];a.u=b.u;a.saturation=b.saturation;a.w=b.w;a.color=b.color;a.C=b.C}else a.u=360*Math.random(),a.saturation=50+50*Math.random(),a.w=50+40*Math.random()}
function ea(a){a.color="hsl("+a.u+","+a.saturation+"%,"+a.w+"%)";a.C=r.context.createRadialGradient(0,0,0,0,0,2);for(var b=.5,c=20;0<=c;--c)a.C.addColorStop((.5+c/20*.3)/2,"hsla("+a.u+","+a.saturation+"%,"+a.w+"%, "+b+")"),b/=1.14;a.C.addColorStop(.45,"hsl("+a.u+","+a.saturation+"%,"+a.w+"%)");a.C.addColorStop(.475,"hsl("+a.u+","+a.saturation+"%,"+Math.min(90,a.w+20)+"%)");a.C.addColorStop(.5,"hsla("+a.u+","+a.saturation+"%,"+Math.min(90,a.w+20)+"%, 0.6)");a.C.addColorStop(.5005,"hsla("+a.u+","+a.saturation+
"%,"+a.w+"%, 0.2)");a.C.addColorStop(.75,"hsla("+a.u+","+a.saturation+"%,"+a.w+"%, 0.05)");a.C.addColorStop(1,"transparent")}
y.prototype.J=function(a){if(!(this.f+2*this.a<v.f-r.canvas.width/2/r.j/v.zoom||this.f-2*this.a>v.f+r.canvas.width/2/r.j/v.zoom||this.i+2*this.a<v.i-r.canvas.height/2/r.j/v.zoom||this.i-2*this.a>v.i+r.canvas.height/2/r.j/v.zoom||1>=this.a*v.zoom)){a.translate(this.f,this.i);if(d.R&&6<=this.a*v.zoom){a.scale(this.a/20,this.a/20);var b=this.I();var c=1E6<=b?.45:1E5<=b?.55:1E4<=b?.7:1E3<=b?.85:1;if(1!=this.T){var f=.3*Math.cos((this.T-.3)*Math.PI/1.4)+1;a.scale(f*c,f*c)}else 1!=c&&a.scale(c,c);a.fillStyle=
this.color;a.fillText(b,0,5);1!=this.T?a.scale(1/f/c,1/f/c):1!=c&&a.scale(1/c,1/c);a.scale(20,20)}else a.scale(this.a,this.a);a.beginPath();a.arc(0,0,2,0,2*Math.PI);a.fillStyle=this.C;a.fill();a.drawImage(this.qa,-1,-1,2,2);a.scale(1/this.a,1/this.a);a.translate(-this.f,-this.i)}};y.prototype.qa=new Image;d.ra(y.prototype.qa);y.prototype.qa.src="images/reflection.png";
var D=new function(){this.la=document.getElementById("bar");this.Y=document.getElementById("scaleBar");this.progress=this.la.children[0];this.B=function(){this.la.style.opacity=0;this.Y.style.opacity=0};this.show=function(){this.la.style.opacity=1;this.Y.style.opacity=1};this.set=function(a){a=100*a+"%";this.progress.style.width!=a&&(this.progress.style.width=a)};this.F=function(a){var b="hsl("+a.u+","+a.saturation+"%,"+.75*a.w+"%)";this.progress.style.backgroundImage='url("images/bar.png"), linear-gradient('+
b+",hsl("+(a.u+","+a.saturation+"%,"+a.w+"%),")+b+")";this.progress.style.boxShadow="-10px -10px 20px 10px "+a.color;this.Y.style.color=a.color};this.ga=function(a){this.Y.innerHTML!=a&&(this.Y.innerHTML=a)};this.update=function(a){if(null==a)this.set(0),this.ga("");else{var b=B.ba(x,a.a);0==b?(b=B.W(1),this.set(B.ta(a)/b),this.ga(B.ma(b))):(this.set(b-Math.floor(b)),1E3>b?this.ga(B.ma(B.W(Math.floor(b+1)))):this.ga(""))}}},v=new function(){this.i=this.f=0;this.A=this.zoom=1;this.Z=!1;this.U=0;this.reset=
function(){this.i=this.f=0;this.A=this.zoom=1;this.Z=!1;this.U=0}},r=new function(){this.context=this.canvas=null;this.j=1;this.M=function(){this.canvas=document.getElementById("screen");this.context=this.canvas.getContext("2d");this.Fa()};this.Fa=function(){this.j=window.devicePixelRatio||1;if(this.canvas.width!=window.innerWidth*this.j||this.canvas.height!=window.innerHeight*this.j)this.canvas.width=window.innerWidth*this.j,this.canvas.height=window.innerHeight*this.j};this.update=function(){this.Fa();
ca.J(this.context);this.context.translate(Math.floor(this.canvas.width/2),Math.floor(this.canvas.height/2));this.context.scale(v.zoom*this.j,v.zoom*this.j);this.context.translate(-v.f,-v.i);var a=this.context;a.font="20px Sadana";a.textAlign="center";for(a=0;a<E.length;++a)E[a].J(this.context);this.context.setTransform(1,0,0,1,0,0);ia.J(this.context);ba.J(this.context);d.J(this.context)}},aa=new function(){this.info=document.getElementById("info");this.show=function(){this.info.className=""};this.B=
function(){this.info.className="hidden"};this.F=function(a){this.info.style.color=a.color}},e=new function(){this.aa=0;this.D=null;this.loaded=!1;try{document.domain="awilh37.github.io",window.parent.kongregateAPI?window.parent.kongregateAPI.loadAPI(function(){e.loaded=!0;e.D=window.parent.kongregateAPI.getAPI();d.P()}):(this.loaded=!0,d.P())}catch(a){console.error(a),this.loaded=!0,d.P()}this.Ra=function(){null!=this.D&&this.D.stats.submit("Initialized",1)};this.za=null;this.Ta=function(){var a=B.I(F.G,
F.H);G||null==this.D||a==this.za||(this.D.stats.submit("TotalLevel",a),this.za=a)};this.va=null;this.Pa=function(){var a=B.I(F.G,F.H)-I;G||null==this.D||a==this.va||(this.D.stats.submit("Level",a),this.va=a)};this.wa=null;this.Qa=function(){var a=B.ba(F.G,F.H)-I;G||null==this.D||a==this.wa||(this.D.stats.submit("LevelFloat",1E4*a),this.wa=a)};this.ua=null;this.Oa=function(){var a=F.K;G||null==this.D||a==this.ua||(this.D.stats.submit("Absorbed",a),this.ua=a)};this.ya=null;this.Sa=function(){var a=
F.time;G||null==this.D||a==this.ya||(this.D.stats.submit("Time",Math.floor(1E3*a)),this.ya=a)};this.refresh=function(){null!=t&&J&&(this.Ta(),this.Pa(),this.Qa(),this.Oa(),this.Sa())};this.update=function(a){this.aa+=a;.5<=this.aa&&(this.refresh(),this.aa=0)}},m=new function(){this.message=document.getElementById("message");this.B=function(){this.message.style.opacity=0};this.show=function(a){this.message.innerHTML=a;this.message.style.opacity=1};this.F=function(a){this.message.style.color=a.color}},
ja=new function(){this.da=[];this.S=[];this.Da=!1;this.enabled=!0;this.M=function(){for(var a=["audio/not_to_notice","audio/decline"],b=0;b<a.length;++b){var c=document.createElement("audio");c.setAttribute("preload","auto");c.volume=.75;var f=this;c.onended=function(){f.Ca()};var g=document.createElement("source");g.setAttribute("src",a[b]+".ogg");g.setAttribute("type","audio/ogg");c.appendChild(g);g=document.createElement("source");g.setAttribute("src",a[b]+".mp3");g.setAttribute("type","audio/mpeg");
c.appendChild(g);document.body.appendChild(c);this.da.push(c)}this.ia()};this.toggle=function(){this.enabled=!this.enabled;for(var a=0;a<this.da.length;++a)this.da[a].volume=this.enabled?.75:0};this.ia=function(){if(!this.Da)try{this.Ca()}catch(a){}};this.Ca=function(){0==this.S.length&&(this.S=this.da.slice(0));var a=Math.floor(Math.random()*this.S.length);this.S[a].play();this.S[a].paused||(this.Da=!0,this.S.splice(a,1))}},ka=new function(){this.Ba=document.getElementById("pause");this.X=this.fa=
!1;this.pause=function(){this.fa&&(this.X=!0,D.B(),B.B(),F.show(),m.show("Press SPACE to resume"),this.Ba.className="enabled")};this.resume=function(){this.X&&(this.X=!1,D.show(),B.show(),F.B(),m.B(),this.Ba.className="")};this.Ea=function(){this.fa&&(this.X?this.resume():this.pause())}},B=new function(){this.scale=document.getElementById("scale");this.xa=null;this.B=function(){this.scale.style.opacity=0};this.show=function(){this.scale.style.opacity=1};this.F=function(a){this.scale.style.color=a.color};
this.I=function(a,b){return Math.floor(this.ba(a,b))};this.ba=function(a,b){if(0>=b)return 0;var c=a+Math.log((b+100)/100)/Math.LN2;return 1>c?this.W(c)/this.W(1):c};this.W=function(a){return 200*(Math.pow(2,a)-1)};this.Ia=function(a){return this.W(this.ba(x,a))};this.ta=function(a){return this.Ia(a.a)};this.ma=function(a){if(a>9460730472580800*1E12){a/=9460730472580800*1E12;var b="ly"}else a>149597870700*1E12?(a/=149597870700*1E12,b="au"):1E15<a?(a/=1E15,b="km"):1E12<a?(a/=1E12,b="m"):1E9<a?(a/=
1E9,b="mm"):1E6<a?(a/=1E6,b="&micro;m"):1E3<a?(a/=1E3,b="nm"):b="pm";a=Math.floor(1E3*a)/1E3;var c=Math.abs(parseInt(a,10)).toString(),f="";if(1E15<Math.abs(a)){var g=Math.abs(a);for(c=0;10<=g;)++c,g/=10;0>a&&(f="-"+f);f+=Math.trunc(g);var h=Math.trunc(g);if(g!=h){var n=Math.pow(10,3);a=Math.abs(Math.trunc((g-h)*n)/n);f+="."+a.toString().substring(2)}f+=" &middot; 10<sup>"+c+"</sup>"}else{for(g=c.length-1;0<=g;--g)f=0==(c.length-1-g)%3&&g!=c.length-1?c[g]+"&thinsp;"+f:c[g]+f;0>a&&(f="-"+f);h=Math.trunc(a);
a!=h&&(n=Math.pow(10,3),a=Math.abs(Math.trunc(a*n-h*n)/n),f+="."+a.toString().substring(2))}return f+" "+b};this.update=function(a){null==a?this.scale.innerHTML="":(a=1E3>a.I()?this.ma(this.ta(a)):"",a!=this.xa&&(this.xa=this.scale.innerHTML=a))}},F=new function(){this.ja=document.getElementById("stats");this.K=this.H=this.G=null;this.time=0;this.M=function(a){this.G=x;this.H=a.a;this.time=this.K=0};this.Ja=function(){return{g:this.G,r:this.H,b:this.K,t:this.time}};this.Na=function(){var a=K.st;if(a.hasOwnProperty("g")&&
a.hasOwnProperty("r")&&a.hasOwnProperty("b")&&a.hasOwnProperty("t")){if(this.G=parseFloat(a.g),this.H=parseFloat(a.r),this.K=parseInt(a.b,10),this.time=parseFloat(a.t),isNaN(this.G)||isNaN(this.H)||isNaN(this.K)||isNaN(this.time))throw"Stats loading error: Invalid data";}else throw"Stats loading error: Missing data";};this.Ka=function(){var a=this.time,b=Math.floor(a/60/60),c=Math.floor(a/60)-60*b;a=Math.floor(a)-60*c-3600*b;return 0==b?0==c?a+"s":c+"m "+a+"s":b+"h "+c+"m "+a+"s"};this.update=function(a){this.time+=
a};this.B=function(){this.ja.style.opacity=0};this.show=function(){var a="<b>Levels</b><p>"+(B.I(this.G,this.H)-I)+"</p>";a+="<b>Bubbles absorbed</b><p>"+this.K+"</p>";a+="<b>Time</b><p>"+this.Ka()+"</p>";this.ja.innerHTML=a;this.ja.style.opacity=1};this.F=function(a){this.ja.style.color=a.color}};Math.trunc||(Math.trunc=function(a){a=+a;return a-a%1||(isFinite(a)&&0!==a?0>a?-0:0:a)});
var ba=new function(){this.visible=!1;this.opacity=0;this.sa=this.color="#fff";this.F=function(a){this.color="hsl("+a.u+","+a.saturation+"%,"+a.w+"%)";this.sa="hsl("+a.u+","+a.saturation+"%,"+Math.min(90,a.w+20)+"%)"};this.B=function(){this.visible=!1};this.show=function(){this.visible=!0};this.update=function(a){this.opacity=this.visible?Math.min(1,this.opacity+a):Math.max(0,this.opacity-4*a)};this.J=function(a){0<this.opacity&&(a.globalAlpha=this.opacity,a.fillStyle=this.sa,a.shadowColor=this.color,
a.shadowBlur=20*r.j,a.textAlign="center",a.font=480>a.canvas.width/r.j?70*r.j+"px Sadana":530>a.canvas.width/r.j?100*r.j+"px Sadana":670>a.canvas.width/r.j?120*r.j+"px Sadana":150*r.j+"px Sadana",a.fillText("Big Bubbles",a.canvas.width/2,a.canvas.height/4-40*r.j),a.shadowBlur=0,a.globalAlpha=1)}},ia=new function(){this.isEnabled=!1;this.J=function(a){this.isEnabled&&(a.strokeStyle="rgba(255,255,255,0.25)",a.fillStyle="rgba(255,255,255,0.1)",a.beginPath(),a.arc(a.canvas.width/2,a.canvas.height-128*
r.j,48*r.j,0,2*Math.PI),L&&(a.moveTo(a.canvas.width/2,a.canvas.height-128*r.j),a.lineTo(la*r.j,ma*r.j)),a.fill(),a.stroke())};this.update=function(){if(na||M||N||O||P)this.isEnabled=!1;L&&(this.isEnabled=!0);J||(this.isEnabled=!1);if(null==t)this.isEnabled=!1;else if(0==t.a||0==x&&1>=t.a)this.isEnabled=!1}},J=!1,oa=null,G=!1,x=0,pa=0,Q=null,R=null,S=null,qa=0,T=1,I=1,E=[],t=null,M=!1,N=!1,O=!1,P=!1,ra=!1,sa=!1,ta=0,ua=0,na=!1,la=0,ma=0,L=!1,va=!1,wa=!1,xa=!1;
function U(){J=!1;m.B();F.B();D.show();B.show();m.show("<b>W A S D / MOUSE</b> - move<br><b>Q E / SCROLL</b> - zoom");x=Math.max(0,5*Math.floor(T/5)-1);A.length=0;E=[];t=new y;t.a=100;z(t);E.push(t);I=B.I(x,t.a);sa=ra=P=O=N=M=!1;ya();pa=0;S=R=Q=t.a;qa=0;v.reset();v.zoom=100/t.a;F.M(t);V=t.f;W=t.i;X=t.a;za=0;Aa=!1}
function Ba(a){var b="version"+a.version;b+="gs"+a.gs;b+="r"+a.r;b+="h"+a.h;b+="s"+a.s;b+="l"+a.l;4==a.version&&(b+="c"+a.c,b+="sl"+a.sl);b+="st.g"+a.st.g;b+="st.r"+a.st.r;b+="st.b"+a.st.b;b+="st.t"+a.st.t;for(var c=a=0;c<b.length;++c)a=(a<<5)-a+b.charCodeAt(c),a|=0;return a}var Ca=!1;function ya(){var a=t;D.F(a);aa.F(a);d.F(a);m.F(a);B.F(a);F.F(a);ba.F(a)}var Y=0,Da=(new Date).getTime();
window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};var V,W,X,za=0,Aa=!0;
function Ea(){var a=Y;if(null!=t){var b=t.f-V,c=t.i-W,f=128*X,g=128*X,h=128*Q,n=128*Q,l=.5*Q;if(0<t.a){var k=function(Ja,Ka){var H=new y;H.a=Math.pow(Math.random(),5)*Q*12+Math.random()*Q;z(H);H.f=Ja;H.i=Ka;H.m=(Math.random()-.5)*(Math.random()-.5)*8*H.a;H.o=(Math.random()-.5)*(Math.random()-.5)*8*H.a;E.push(H)};if(Aa){for(var p=0;p<h*n/h/l;++p){var w=-h+2*Math.random()*h,C=-n+2*Math.random()*n;w*w+C*C>2500*t.a*t.a&&k(t.f+w,t.i+C)}Aa=!1}for(p=0;p<E.length;++p){var q=E[p];q!=t&&(q.a<Q/30&&(q.volume*=
1-5*a,ha(q)),q.f-t.f<-h-q.a||q.f-t.f>h+q.a||q.i-t.i<-n-q.a||q.i-t.i>n+q.a||q.a<Q/1E3)&&(fa(q),E.splice(p,1),--p)}p=(h*n-f*g)/h/l+za;a=Math.floor(p);za=p-a;for(p=0;p<a;++p){do w=-h+2*Math.random()*h,C=-n+2*Math.random()*n;while(w>=-f&&w<=f&&C>=-g&&C<=g);k(t.f+w,t.i+C)}for(X=Q;b>=l;)b-=l,V+=l,k(t.f+h-q.a+Math.random()*q.a*2,t.i-n-q.a+Math.random()*(2*n+2*q.a));for(;b<=-l;)b+=l,V-=l,k(t.f-h-q.a+Math.random()*q.a*2,t.i-n-q.a+Math.random()*(2*n+2*q.a));for(;c>=l;)c-=l,W+=l,k(t.f-h-q.a+Math.random()*(2*
h+2*q.a),t.i+n-q.a+Math.random()*q.a*2);for(;c<=-l;)c+=l,W-=l,k(t.f-h-q.a+Math.random()*(2*h+2*q.a),t.i-n-q.a+Math.random()*q.a*2)}}}
function Fa(){var a=(new Date).getTime();Y=(a-Da)/1E3;Da=a;0>Y&&(Y=0);.1<Y&&(Y=.1);if(0<Y){a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():[];for(var b=!1,c=!1,f=!1,g=0;g<a.length;++g){var h=a[g];if(h&&"standard"==h.mapping&&(4<=h.buttons.length&&(h.buttons[0].pressed||h.buttons[1].pressed||h.buttons[2].pressed||h.buttons[3].pressed)&&J&&(null!=t?0==t.a&&U():U()),9<=h.buttons.length&&(h.buttons[8].pressed||h.buttons[9].pressed)&&(b=!0),5<=
h.buttons.length&&(h.buttons[5].pressed&&(c=!0,Z()),h.buttons[4].pressed&&(f=!0,Z())),4<=h.axes.length)){var n=Math.abs(h.axes[0])>Math.abs(h.axes[2])?h.axes[0]:h.axes[2];h=Math.abs(h.axes[1])>Math.abs(h.axes[3])?h.axes[1]:h.axes[3];.1<Math.sqrt(n*n+h*h)&&Z()}}wa=c;xa=f;!va&&b&&ka.Ea();va=b;if(!ka.X){a=Y;if(null!=t)if(0==t.a||0==x&&1>=t.a)e.refresh(),ka.fa=!1,m.show("Press R / CLICK to restart"),D.B(),B.B(),F.show(),t.a=0,t=null,L=na=!1;else{R=Q;for(pa+=a;pa>=1/300;)Q=.99*Q+.01*t.a,pa-=1/300;b=B.I(x,
t.a);b!=B.I(x,S)&&t.a>S&&(u.Ma(),t.T=0);T=Math.max(T,b);S=t.a;t.m=Math.max(-1E5,Math.min(1E5,t.m));t.o=Math.max(-1E5,Math.min(1E5,t.o));for(qa+=a;qa>=1/300;)t.m*=.995,t.o*=.995,qa-=1/300;if(J)if(b=40*t.a,L)c=la-window.innerWidth/2,g=ma-(window.innerHeight-128),0!=c&&0!=g&&(f=Math.atan2(g,c),c=Math.sqrt(c*c+g*g),c=Math.min(1,c/96),t.m+=b*c*a*Math.cos(f),t.o+=b*c*a*Math.sin(f));else if(na)c=ta-window.innerWidth/2,g=ua-window.innerHeight/2,0!=c&&0!=g&&(f=Math.atan2(g,c),c=Math.sqrt(c*c+g*g),c=Math.min(1,
c/128),t.m+=b*c*a*Math.cos(f),t.o+=b*c*a*Math.sin(f));else if(M||N||O||P)(M&&!N||!M&&N)&&(O&&!P||!O&&P)&&(b/=Math.SQRT2),M&&(t.o-=b*a),N&&(t.o+=b*a),O&&(t.m-=b*a),P&&(t.m+=b*a);else for(f=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():[],g=0;g<f.length;++g)if((c=f[g])&&"standard"==c.mapping&&4<=c.axes.length&&(n=Math.abs(c.axes[0])>Math.abs(c.axes[2])?c.axes[0]:c.axes[2],h=Math.abs(c.axes[1])>Math.abs(c.axes[3])?c.axes[1]:c.axes[3],c=Math.sqrt(n*
n+h*h),.1<c)){1<c&&(n/=c,h/=c);t.m+=b*a*n;t.o+=b*a*h;break}x>F.G?(F.G=x,F.H=t.a):x==F.G&&(F.H=Math.max(t.a,F.H))}if(J){try{a=!1;if(null!=oa)if(null!=localStorage.getItem("current")){var l=JSON.parse(localStorage.current);if(3!=l.version&&4!=l.version)a=!0;else{var k=l.v;Ba(l)!=k?a=!0:k!=oa&&(a=!0)}}else a=!0;else null!=localStorage.getItem("current")&&(a=!0);a&&(G=!0)}catch(C){}try{if(G)throw"Invalid session";if(null==t||0==t.a){var p=Math.max(0,5*Math.floor(T/5)-1);var w={version:4,gs:p,r:100,h:360*
Math.random(),s:50+50*Math.random(),l:50+40*Math.random(),c:T,sl:I,st:{g:p,r:100,b:0,t:0}}}else w={version:4,gs:x,r:t.a,h:t.u,s:t.saturation,l:t.w,c:T,sl:I,st:F.Ja()};oa=Ba(w);w.v=oa;localStorage.current=JSON.stringify(w)}catch(C){Ca||(console.warn("Save failed: "+C),Ca=!0)}}Ea();k=Y;for(l=0;l<E.length;++l)E[l].update(k);for(l=0;l<E.length;++l)for(k=E[l],w=l+1;w<E.length;++w)if(p=E[w],c=(k.f-p.f)*(k.f-p.f)+(k.i-p.i)*(k.i-p.i),c<(k.a+p.a)*(k.a+p.a))if(k!=t&&p!=t||u.La(k,p),p.volume>k.volume?(a=k,b=
p):(a=p,b=k),c<=b.a*b.a)if(b.m+=(a.m-b.m)*a.volume/b.volume,b.o+=(a.o-b.o)*a.volume/b.volume,b.volume+=a.volume,ha(b),a.volume=0,a.a=0,b==t&&++F.K,p.volume>k.volume){fa(k);E.splice(l,1);--l;break}else fa(p),E.splice(w,1),--w;else if(c=a.a+b.a-Math.sqrt(c),c=a.volume-4/3*Math.PI*(a.a-c)*(a.a-c)*(a.a-c),b.m+=(a.m-b.m)*c/b.volume,b.o+=(a.o-b.o)*c/b.volume,a.volume-=c,b.volume+=c,ha(b),0>=a.volume)if(a.volume=0,a.a=0,b==t&&++F.K,p.volume>k.volume){fa(k);E.splice(l,1);--l;break}else fa(p),E.splice(w,1),
--w;else ha(a);if(null!=t&&0<t.a){for(;20>Q&&0<x;){for(l=0;l<E.length;++l)k=E[l],k.f*=2,k.i*=2,k.m*=2,k.o*=2,k.a*=2,z(k);Q*=2;R*=2;S*=2;V*=2;W*=2;X*=2;v.f*=2;v.i*=2;v.zoom/=2;v.A/=2;--x}for(;5E3<Q;){for(l=0;l<E.length;++l)k=E[l],k.f/=2,k.i/=2,k.m/=2,k.o/=2,k.a/=2,z(k);Q/=2;R/=2;S/=2;V/=2;W/=2;X/=2;v.f/=2;v.i/=2;v.zoom*=2;v.A*=2;x+=1}}l=Y;if(null!=t&&0<t.a){v.f=t.f;v.i=t.i;if(v.Z)for(v.U+=l;v.U>=1/300&&v.Z;)v.zoom=.97*v.zoom+.03*v.A,5E-5>Math.abs(v.zoom-v.A)&&(v.Z=!1),v.U-=1/300;if(J){if(ra||wa)v.zoom*=
1+3*l,v.A*=1+3*l;if(sa||xa)v.zoom*=1-3*l,v.A*=1-3*l}v.zoom*=R/Q;v.A*=R/Q;l=Math.max(r.canvas.width,r.canvas.height)/r.j/Q/7;k=Math.max(r.canvas.width,r.canvas.height)/r.j/Q/200;v.zoom=Math.max(k,Math.min(l,v.zoom));v.A=Math.max(k,Math.min(l,v.A))}ca.update(Y);J&&F.update(Y)}e.update(Y);u.update();r.update();D.update(t);B.update(t);ia.update();ba.update(Y);d.update(Y)}requestAnimFrame(Fa)}u.M();ja.M();r.M();Fa();J=!1;B.B();F.B();var Ga=!1;
try{if(null!=localStorage.getItem("current")){var K=JSON.parse(localStorage.current);if(3!=K.version&&4!=K.version)throw localStorage.removeItem("current"),"Incompatible version";var Ha=K.v;if(Ba(K)!=Ha)throw localStorage.removeItem("current"),"Corrupt save";oa=Ha;x=parseInt(K.gs,10);4==K.version?(T=parseInt(K.c,10),I=parseInt(K.sl,10)):I=T=1;if(isNaN(x)||isNaN(T)||1>T||isNaN(I)||1>I)throw localStorage.removeItem("current"),"Corrupt save";A.length=0;t=new y;t.a=parseFloat(K.r);t.u=parseFloat(K.h);
t.saturation=parseFloat(K.s);t.w=parseFloat(K.l);if(isNaN(t.a)||0>t.a||isNaN(t.u)||0>t.u||360<t.u||isNaN(t.saturation)||0>t.saturation||100<t.saturation||isNaN(t.w)||0>t.w||100<t.w)throw localStorage.removeItem("current"),"Corrupt save";z(t);ea(t);F.Na();E=[t]}else throw"No save found";}catch(a){console.warn("Failed to load save: "+a),Ga=!0}Ga&&(oa=null,x=0,I=T=1,A.length=0,t=new y,t.a=100,z(t),E=[t],F.M(t));pa=0;S=R=Q=t.a;qa=0;ya();v.reset();v.zoom=100/t.a;V=t.f;W=t.i;X=t.a;za=0;Aa=!1;
function Z(){!J&&d.na()&&(J=!0,v.A=Math.max(r.canvas.width,r.canvas.height)/r.j/Q/100,v.Z=!0,ka.fa=!0,ba.B(),m.B(),aa.B(),D.show(),B.show(),Aa=!0,e.Ra())}
function Ia(a){if(a.code)return a.code;if(a.keyCode)switch(a.keyCode){case 27:return"Escape";case 32:return"Space";case 37:return"ArrowLeft";case 38:return"ArrowUp";case 39:return"ArrowRight";case 40:return"ArrowDown";case 65:return"KeyA";case 67:return"KeyC";case 68:return"KeyD";case 69:return"KeyE";case 76:return"KeyL";case 77:return"KeyM";case 80:return"KeyP";case 81:return"KeyQ";case 82:return"KeyR";case 83:return"KeyS";case 87:return"KeyW"}}
window.addEventListener("keydown",function(a){a=a||window.event;var b=Ia(a);"ArrowUp"!=b&&"KeyW"!=b&&"ArrowDown"!=b&&"KeyS"!=b&&"ArrowLeft"!=b&&"KeyA"!=b&&"ArrowRight"!=b&&"KeyD"!=b&&"KeyE"!=b&&"KeyQ"!=b||Z();"KeyC"!=b||J||null==t||(A.length=0,t.color=null,t.C=null,da(t),ea(t),ya());if(J){null!=t?0==t.a&&"KeyR"==b&&U():"KeyR"==b&&U();if("ArrowUp"==b||"KeyW"==b)M=!0;if("ArrowDown"==b||"KeyS"==b)N=!0;if("ArrowLeft"==b||"KeyA"==b)O=!0;if("ArrowRight"==b||"KeyD"==b)P=!0;"KeyE"==b&&(ra=!0);"KeyQ"==b&&
(sa=!0);"KeyM"==b&&ja.toggle()}null!=u.context&&"running"!=u.context.state&&u.context.resume();ja.ia();"Escape"!=b&&"Space"!=b&&"ArrowLeft"!=b&&"ArrowUp"!=b&&"ArrowRight"!=b&&"ArrowDown"!=b&&"KeyA"!=b&&"KeyC"!=b&&"KeyD"!=b&&"KeyE"!=b&&"KeyL"!=b&&"KeyP"!=b&&"KeyQ"!=b&&"KeyR"!=b&&"KeyS"!=b&&"KeyW"!=b&&"KeyM"!=b||a.preventDefault()});
window.addEventListener("keyup",function(a){a=a||window.event;var b=Ia(a);"Space"!=b&&"Escape"!=b&&"KeyP"!=b||ka.Ea();if("ArrowUp"==b||"KeyW"==b)M=!1;if("ArrowDown"==b||"KeyS"==b)N=!1;if("ArrowLeft"==b||"KeyA"==b)O=!1;if("ArrowRight"==b||"KeyD"==b)P=!1;"KeyE"==b&&(ra=!1);"KeyQ"==b&&(sa=!1);"Escape"!=b&&"Space"!=b&&"ArrowLeft"!=b&&"ArrowUp"!=b&&"ArrowRight"!=b&&"ArrowDown"!=b&&"KeyA"!=b&&"KeyC"!=b&&"KeyD"!=b&&"KeyE"!=b&&"KeyL"!=b&&"KeyP"!=b&&"KeyQ"!=b&&"KeyR"!=b&&"KeyS"!=b&&"KeyW"!=b||a.preventDefault()});
window.addEventListener("mousedown",function(){na=!0;Z();null!=u.context&&"running"!=u.context.state&&u.context.resume();ja.ia()});window.addEventListener("mouseup",function(){na&&J&&(null!=t?0==t.a&&U():U());na=!1});window.addEventListener("mousemove",function(a){ta=a.clientX;ua=a.clientY});window.addEventListener("wheel",function(a){Z();d.na()&&(0>a.deltaY?(v.zoom*=1.2,v.A*=1.2):0<a.deltaY&&(v.zoom*=.8,v.A*=.8));a.preventDefault()});
window.addEventListener("touchstart",function(a){L=!0;0<a.touches.length&&(la=a.touches[0].pageX,ma=a.touches[0].pageY);Z();null!=u.context&&"running"!=u.context.state&&u.context.resume();ja.ia()});window.addEventListener("touchend",function(){L&&J&&(null!=t?0==t.a&&U():U());L=!1});window.addEventListener("touchmove",function(a){0<a.touches.length&&(la=a.touches[0].pageX,ma=a.touches[0].pageY)});
